In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings; warnings.simplefilter('ignore')

In [2]:
#Load DataSet
dataset=pd.read_csv('C:/Users/gnanam.natarajan/Desktop/project/inputdata/city_day.csv',encoding="ISO-8859-1")
dataset.describe()

PM2.5          PM10            NO           NO2           NOx  \
count  24933.000000  18391.000000  25949.000000  25946.000000  25346.000000   
mean      67.450578    118.127103     17.574730     28.560659     32.309123   
std       64.661449     90.605110     22.785846     24.474746     31.646011   
min        0.040000      0.010000      0.020000      0.010000      0.000000   
25%       28.820000     56.255000      5.630000     11.750000     12.820000   
50%       48.570000     95.680000      9.890000     21.690000     23.520000   
75%       80.590000    149.745000     19.950000     37.620000     40.127500   
max      949.990000   1000.000000    390.680000    362.210000    467.630000   

                NH3            CO           SO2            O3       Benzene  \
count  19203.000000  27472.000000  25677.000000  25509.000000  23908.000000   
mean      23.483476      2.248598     14.531977     34.491430      3.280840   
std       25.684275      6.962884     18.133775     21.694928     15.811136   
min        0.010000      0.000000      0.010000      0.010000      0.000000   
25%        8.580000      0.510000      5.670000     18.860000      0.120000   
50%       15.850000      0.890000      9.160000     30.840000      1.070000   
75%       30.020000      1.450000     15.220000     45.570000      3.080000   
max      352.890000    175.810000    193.860000    257.730000    455.030000   

            Toluene        Xylene           AQI  
count  21490.000000  11422.000000  24850.000000  
mean       8.700972      3.070128    166.463581  
std       19.969164      6.323247    140.696585  
min        0.000000      0.000000     13.000000  
25%        0.600000      0.140000     81.000000  
50%        2.970000      0.980000    118.000000  
75%        9.150000      3.350000    208.000000  
max      454.850000    170.370000   2049.000000

In [3]:
df=dataset.dropna()
df.head(10)


City        Date  PM2.5    PM10    NO    NO2    NOx    NH3    CO  \
2123  Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72  0.12   
2124  Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28  0.14   
2125  Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91  0.11   
2126  Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42  0.09   
2127  Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25  0.16   
2128  Amaravati  2017-11-30  69.80  114.86  4.69  20.17  14.54  10.95  0.12   
2129  Amaravati  2017-12-01  73.96  113.56  4.58  19.29  13.97  10.95  0.10   
2130  Amaravati  2017-12-02  89.90  140.20  7.71  26.19  19.87  13.12  0.10   
2131  Amaravati  2017-12-03  87.14  130.52  0.97  21.31  12.12  14.36  0.15   
2132  Amaravati  2017-12-04  84.64  125.00  4.02  26.98  17.58  14.41  0.18   

        SO2      O3  Benzene  Toluene  Xylene    AQI AQI_Bucket  
2123  15.24  127.09     0.20     6.50    0.06  184.0   Moderate  
2124  26.96  117.44     0.22     7.95    0.08  197.0   Moderate  
2125  33.59  111.81     0.29     7.63    0.12  198.0   Moderate  
2126  19.00  138.18     0.17     5.02    0.07  188.0   Moderate  
2127  10.55  109.74     0.21     4.71    0.08  173.0   Moderate  
2128  14.07  118.09     0.16     3.52    0.06  165.0   Moderate  
2129  13.90  123.80     0.17     2.85    0.04  191.0   Moderate  
2130  19.37  128.73     0.25     2.79    0.07  191.0   Moderate  
2131  11.41  114.80     0.23     3.82    0.04  227.0       Poor  
2132   9.84  112.41     0.31     3.53    0.09  168.0   Moderate

In [4]:
df.shape


(6236, 16)

In [5]:
df.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [6]:
del df["Date"]

In [7]:
del df["AQI_Bucket"]

In [8]:
X = df.iloc[:, :-1].values
#Response variable
y = df.iloc[:, -1].values
#y = df.iloc[:, ].values

In [9]:
print(X)

print(y)

[['Amaravati' 81.4 124.5 ... 0.2 6.5 0.06]
 ['Amaravati' 78.32 129.06 ... 0.22 7.95 0.08]
 ['Amaravati' 88.76 135.32 ... 0.29 7.63 0.12]
 ...
 ['Visakhapatnam' 24.38 74.09 ... 0.74 2.21 0.38]
 ['Visakhapatnam' 22.91 65.73 ... 0.01 0.01 0.0]
 ['Visakhapatnam' 16.64 49.97 ... 0.0 0.0 0.0]]
[184. 197. 198. ...  70.  68.  54.]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 0.2 6.5 0.06]
 [1.0 0.0 0.0 ... 0.22 7.95 0.08]
 [1.0 0.0 0.0 ... 0.29 7.63 0.12]
 ...
 [0.0 0.0 0.0 ... 0.74 2.21 0.38]
 [0.0 0.0 0.0 ... 0.01 0.01 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.tree import DecisionTreeClassifier
    
gnb = DecisionTreeClassifier()    
gnb=gnb.fit(X_train, y_train)

In [14]:
from sklearn.metrics import accuracy_score
y_pred=gnb.predict(X_test)

In [15]:
gnb.predict([[1, 0, 0, 0, 0, 0, 0, 0, 0, '81.4', '124.5', '1.44', '20.5', '12.08', '10.72', '0.12', '15.24', '127.09', '0.2', '6.5', '0.06']])

array([184.])

In [17]:
df['AQI'].unique

<bound method Series.unique of 2123     184.0
2124     197.0
2125     198.0
2126     188.0
2127     173.0
2128     165.0
2129     191.0
2130     191.0
2131     227.0
2132     168.0
2133     198.0
2134     201.0
2135     252.0
2136     310.0
2137     196.0
2138     132.0
2139     147.0
2140     179.0
2141     145.0
2142     115.0
2143     140.0
2144     156.0
2145     225.0
2146     251.0
2147     228.0
2148     223.0
2149     170.0
2150     165.0
2151     159.0
2152     232.0
         ...  
29500     85.0
29501     50.0
29502     88.0
29503     71.0
29504     93.0
29505    101.0
29506     82.0
29507    115.0
29508     96.0
29509     92.0
29510     90.0
29511     84.0
29512     81.0
29513     88.0
29514     92.0
29515     83.0
29516     90.0
29517     71.0
29518    110.0
29519     74.0
29520     92.0
29521     95.0
29522    100.0
29523     86.0
29524     77.0
29525     47.0
29526     41.0
29527     70.0
29528     68.0
29529     54.0
Name: AQI, Length: 6236, dtype: float64>

In [18]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [19]:
regressor.predict([[1, 0, 0, 0, 0, 0, 0, 0, 0, '81.4', '124.5', '1.44', '20.5', '12.08', '10.72', '0.12', '15.24', '127.09', '0.2', '6.5', '0.06']])

array([184.])