In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings; warnings.simplefilter('ignore')

In [2]:
#Load DataSet
dataset=pd.read_csv('C:/Users/gnanam.natarajan/Desktop/project/inputdata/city_day.csv',encoding="ISO-8859-1")
dataset.describe()


PM2.5          PM10            NO           NO2           NOx  \
count  24933.000000  18391.000000  25949.000000  25946.000000  25346.000000   
mean      67.450578    118.127103     17.574730     28.560659     32.309123   
std       64.661449     90.605110     22.785846     24.474746     31.646011   
min        0.040000      0.010000      0.020000      0.010000      0.000000   
25%       28.820000     56.255000      5.630000     11.750000     12.820000   
50%       48.570000     95.680000      9.890000     21.690000     23.520000   
75%       80.590000    149.745000     19.950000     37.620000     40.127500   
max      949.990000   1000.000000    390.680000    362.210000    467.630000   

                NH3            CO           SO2            O3       Benzene  \
count  19203.000000  27472.000000  25677.000000  25509.000000  23908.000000   
mean      23.483476      2.248598     14.531977     34.491430      3.280840   
std       25.684275      6.962884     18.133775     21.694928     15.811136   
min        0.010000      0.000000      0.010000      0.010000      0.000000   
25%        8.580000      0.510000      5.670000     18.860000      0.120000   
50%       15.850000      0.890000      9.160000     30.840000      1.070000   
75%       30.020000      1.450000     15.220000     45.570000      3.080000   
max      352.890000    175.810000    193.860000    257.730000    455.030000   

            Toluene        Xylene           AQI  
count  21490.000000  11422.000000  24850.000000  
mean       8.700972      3.070128    166.463581  
std       19.969164      6.323247    140.696585  
min        0.000000      0.000000     13.000000  
25%        0.600000      0.140000     81.000000  
50%        2.970000      0.980000    118.000000  
75%        9.150000      3.350000    208.000000  
max      454.850000    170.370000   2049.000000

In [3]:
dataset.head(10)


City        Date  PM2.5  PM10      NO    NO2     NOx  NH3      CO  \
0  Ahmedabad  2015-01-01    NaN   NaN    0.92  18.22   17.15  NaN    0.92   
1  Ahmedabad  2015-01-02    NaN   NaN    0.97  15.69   16.46  NaN    0.97   
2  Ahmedabad  2015-01-03    NaN   NaN   17.40  19.30   29.70  NaN   17.40   
3  Ahmedabad  2015-01-04    NaN   NaN    1.70  18.48   17.97  NaN    1.70   
4  Ahmedabad  2015-01-05    NaN   NaN   22.10  21.42   37.76  NaN   22.10   
5  Ahmedabad  2015-01-06    NaN   NaN   45.41  38.48   81.50  NaN   45.41   
6  Ahmedabad  2015-01-07    NaN   NaN  112.16  40.62  130.77  NaN  112.16   
7  Ahmedabad  2015-01-08    NaN   NaN   80.87  36.74   96.75  NaN   80.87   
8  Ahmedabad  2015-01-09    NaN   NaN   29.16  31.00   48.00  NaN   29.16   
9  Ahmedabad  2015-01-10    NaN   NaN     NaN   7.04    0.00  NaN     NaN   

     SO2      O3  Benzene  Toluene  Xylene  AQI AQI_Bucket  
0  27.64  133.36     0.00     0.02    0.00  NaN        NaN  
1  24.55   34.06     3.68     5.50    3.77  NaN        NaN  
2  29.07   30.70     6.80    16.40    2.25  NaN        NaN  
3  18.59   36.08     4.43    10.14    1.00  NaN        NaN  
4  39.33   39.31     7.01    18.89    2.78  NaN        NaN  
5  45.76   46.51     5.42    10.83    1.93  NaN        NaN  
6  32.28   33.47     0.00     0.00    0.00  NaN        NaN  
7  38.54   31.89     0.00     0.00    0.00  NaN        NaN  
8  58.68   25.75     0.00     0.00    0.00  NaN        NaN  
9   8.29    4.55     0.00     0.00    0.00  NaN        NaN

In [4]:
df=dataset.dropna()
df.head(10)


City        Date  PM2.5    PM10    NO    NO2    NOx    NH3    CO  \
2123  Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72  0.12   
2124  Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28  0.14   
2125  Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91  0.11   
2126  Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42  0.09   
2127  Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25  0.16   
2128  Amaravati  2017-11-30  69.80  114.86  4.69  20.17  14.54  10.95  0.12   
2129  Amaravati  2017-12-01  73.96  113.56  4.58  19.29  13.97  10.95  0.10   
2130  Amaravati  2017-12-02  89.90  140.20  7.71  26.19  19.87  13.12  0.10   
2131  Amaravati  2017-12-03  87.14  130.52  0.97  21.31  12.12  14.36  0.15   
2132  Amaravati  2017-12-04  84.64  125.00  4.02  26.98  17.58  14.41  0.18   

        SO2      O3  Benzene  Toluene  Xylene    AQI AQI_Bucket  
2123  15.24  127.09     0.20     6.50    0.06  184.0   Moderate  
2124  26.96  117.44     0.22     7.95    0.08  197.0   Moderate  
2125  33.59  111.81     0.29     7.63    0.12  198.0   Moderate  
2126  19.00  138.18     0.17     5.02    0.07  188.0   Moderate  
2127  10.55  109.74     0.21     4.71    0.08  173.0   Moderate  
2128  14.07  118.09     0.16     3.52    0.06  165.0   Moderate  
2129  13.90  123.80     0.17     2.85    0.04  191.0   Moderate  
2130  19.37  128.73     0.25     2.79    0.07  191.0   Moderate  
2131  11.41  114.80     0.23     3.82    0.04  227.0       Poor  
2132   9.84  112.41     0.31     3.53    0.09  168.0   Moderate

In [5]:
df.shape


(6236, 16)

In [6]:
df.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [7]:
df.describe()

PM2.5         PM10           NO          NO2          NOx  \
count  6236.000000  6236.000000  6236.000000  6236.000000  6236.000000   
mean     61.327365   123.418321    17.015191    31.708190    32.448956   
std      53.709682    85.791491    20.037836    18.784041    27.388129   
min       2.000000     7.800000     0.250000     0.170000     0.170000   
25%      27.927500    66.970000     5.080000    15.977500    14.547500   
50%      47.490000   103.010000    10.060000    28.900000    24.285000   
75%      73.442500   150.770000    19.392500    43.632500    39.622500   
max     639.190000   796.880000   159.220000   140.170000   224.090000   

               NH3           CO          SO2           O3      Benzene  \
count  6236.000000  6236.000000  6236.000000  6236.000000  6236.000000   
mean     20.737070     0.984344    11.514426    36.127691     3.700361   
std      16.088215     1.356161     7.166113    19.553695     5.062159   
min       0.120000     0.000000     0.710000     1.550000     0.000000   
25%      10.390000     0.490000     6.557500    22.357500     0.910000   
50%      14.690000     0.730000     9.875000    32.540000     2.435000   
75%      28.545000     1.060000    14.430000    45.512500     4.620000   
max     166.700000    16.230000    70.390000   162.330000    64.440000   

           Toluene       Xylene          AQI  
count  6236.000000  6236.000000  6236.000000  
mean     10.323696     2.557439   140.510103  
std      12.287223     4.535060    92.738826  
min       0.000000     0.000000    23.000000  
25%       2.210000     0.300000    78.000000  
50%       6.310000     1.250000   112.000000  
75%      13.040000     3.030000   166.000000  
max     103.000000   125.180000   677.000000

In [8]:
df.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [9]:

df['City'].unique()

array(['Amaravati', 'Amritsar', 'Chandigarh', 'Delhi', 'Gurugram',
       'Hyderabad', 'Kolkata', 'Patna', 'Visakhapatnam'], dtype=object)

In [50]:


df['AQI_PRDD'] = df.AQI.map({ '93':'satisfactor', '74':'satisfactor', '71':'satisfactor', '4':'good', '39':'good', '42':'good', '27':'good', '263':'poor', '250':'poor', '249':'poor','258':'poor', '284':'poor', '28':'good', '106':'satisfactor', '44':'good', '62':'satisfactor', '59':'satisfactor', '1':'good', '9':'good', '15':'good', '34':'good','63':'satisfactor', '14':'good', '13':'good', '69':'satisfactor', '37':'good', '2':'good', '5':'good', '66':'satisfactor', '202':'poor', '11':'good', '10':'good','52':'satisfactor', '54':'satisfactor', '246':'poor', '248':'poor', '32':'good', '93':'satisfactor', '226':'poor', '189':'moderate', '124':'moderate', '272':'poor','277':'poor', '278':'poor', '279':'poor', '280':'poor', '87':'satisfactor', '19':'good', '240':'poor', '197':'moderate', '38':'good', '84':'satisfactor','61':'satisfactor', '196':'moderate', '171':'moderate', '23' :'good', '111':'moderate', '43' :'good', '188':'moderate', '203' :'poor' , '16' :'good', '20' :'good','225' :'poor' , '190':'moderate', '26' :'good', '104':'moderate', '25' :'good', '224' :'poor' , '210' :'poor' , '83':'satisfactor', '82':'satisfactor', '233' :'poor' ,'205' :'poor' , '78':'satisfactor', '70':'satisfactor', '211' :'poor' , '179':'moderate', '91':'satisfactor', '49':'good', '134':'moderate', '161':'moderate', '223' :'poor' ,'57':'satisfactor', '73':'satisfactor', '207' :'poor' , '184':'moderate', '48' :'good', '6' :'good', '7' :'good', '194':'moderate', '21' :'good', '50' :'good', '231' :'poor' ,'175':'moderate', '45' :'good', '86':'satisfactor', '243' :'poor' , '232' :'poor' , '18' :'good', '31' :'good', '95':'satisfactor', '237' :'poor' , '217' :'poor' ,'99':'satisfactor', '33' :'good', '176':'moderate', '22' :'good', '29' :'good', '107':'moderate', '17' :'good', '75':'satisfactor', '220' :'poor' , '165':'moderate','149':'moderate', '3' :'good', '245' :'poor' , '239' :'poor' , '72':'satisfactor', '77':'satisfactor', '208' :'poor' , '24' :'good', '198':'moderate', '153':'moderate','53':'satisfactor', '228' :'poor' , '186':'moderate', '51':'satisfactor', '247' :'poor' , '219' :'poor' , '100':'satisfactor', '36' :'good', '204' :'poor' , '30' :'good','221' :'poor' , '229' :'poor' , '187':'moderate', '56':'satisfactor', '230' :'poor' , '192':'moderate', '114':'moderate', '274' :'poor' , '236' :'poor' ,'222' :'poor' , '206' :'poor' , '174':'moderate', '58':'satisfactor', '235' :'poor' , '212' :'poor' , '120':'moderate', '148':'moderate', '242' :'poor' ,'215' :'poor' , '80':'satisfactor', '79':'satisfactor', '67':'satisfactor', '40' :'good', '35' :'good', '185':'moderate', '101':'moderate', '46' :'good', '209' :'poor' ,'169':'moderate', '12' :'good', '47' :'good', '227' :'poor' , '200' :'moderate' , '244' :'poor' , '238' :'poor' , '160':'moderate', '282' :'poor' , '218' :'poor' ,'261' :'poor' , '262' :'poor' , '260' :'poor' , '256' :'poor' , '252' :'poor' , '162':'moderate', '172':'moderate', '156':'moderate', '133':'moderate','116':'moderate', '193':'moderate', '123':'moderate', '65':'satisfactor', '96':'satisfactor', '173':'moderate', '103':'moderate', '8' :'good', '273' :'poor' , '275' :'poor' ,'283' :'poor' , '276' :'poor' , '254' :'poor' , '152':'moderate', '105':'moderate', '64':'satisfactor', '0' :'good', '76':'satisfactor', '127':'moderate', '97':'satisfactor','115':'moderate', '150':'moderate', '142':'moderate', '41' :'good', '102':'moderate', '90':'satisfactor', '132':'moderate', '98':'satisfactor', '199':'moderate', '191':'moderate','157':'moderate', '139':'moderate', '94':'satisfactor', '110':'moderate', '270' :'poor' , '268' :'poor' , '281' :'poor' , '265' :'poor' , '267' :'poor' ,'269' :'poor' , '81':'satisfactor', '128':'moderate', '146':'moderate', '145':'moderate', '129':'moderate', '85':'satisfactor', '117':'moderate', '108':'moderate', '154':'moderate','131':'moderate', '255' :'poor' , '257' :'poor' , '88':'satisfactor', '113':'moderate', '118':'moderate', '167':'moderate', '164':'moderate', '137':'moderate','135':'moderate', '138':'moderate', '109':'moderate', '60':'satisfactor', '177':'moderate', '271' :'poor' , '170':'moderate', '144':'moderate', '166':'moderate','155':'moderate', '136':'moderate', '151':'moderate', '89':'satisfactor', '119':'moderate', '266' :'poor' , '264' :'poor' , '251' :'poor' , '253' :'poor' ,'259' :'poor' , '163':'moderate', '159':'moderate', '241' :'poor' , '214' :'poor' , '122':'moderate', '234' :'poor' , '195':'moderate', '130':'moderate','216' :'poor' , '213' :'poor' , '121':'moderate', '112':'moderate', '168':'moderate', '201' :'poor' , '141':'moderate', '181':'moderate', '143':'moderate','126':'moderate', '182':'moderate', '178':'moderate', '158':'moderate', '140':'moderate', '183':'moderate', '92':'satisfactor', '180':'moderate', '147':'moderate', '55':'satisfactor','184':'moderate'})
#df['AOI_PD']=df.AQI_Bucket.map({'Moderate':3 ,'Good':1,'Poor':0 ,'Satisfactory':4, 'Severe':5 ,'Very Poor':0}) 


#X=df.drop(['Date' ,'Xylene','Toluene','Benzene','PM2.5','City','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','AQI_Bucket','AOI_PD'],axis=1)

In [38]:
X
df['AQI_PRDD'] = df.AQI.map({ '93':'satisfactor', '74':'satisfactor', '71':'satisfactor', '4':'good', '39':'good', '42':'good', '27':'good', '263':'poor', '250':'poor', '249':'poor','258':'poor', '284':'poor', '28':'good', '106':'satisfactor', '44':'good', '62':'satisfactor', '59':'satisfactor', '1':'good', '9':'good', '15':'good', '34':'good','63':'satisfactor', '14':'good', '13':'good', '69':'satisfactor', '37':'good', '2':'good', '5':'good', '66':'satisfactor', '202':'poor', '11':'good', '10':'good','52':'satisfactor', '54':'satisfactor', '246':'poor', '248':'poor', '32':'good', '93':'satisfactor', '226':'poor', '189':'moderate', '124':'moderate', '272':'poor','277':'poor', '278':'poor', '279':'poor', '280':'poor', '87':'satisfactor', '19':'good', '240':'poor', '197':'moderate', '38':'good', '84':'satisfactor','61':'satisfactor', '196':'moderate', '171':'moderate', '23' :'good', '111':'moderate', '43' :'good', '188':'moderate', '203' :'poor' , '16' :'good', '20' :'good','225' :'poor' , '190':'moderate', '26' :'good', '104':'moderate', '25' :'good', '224' :'poor' , '210' :'poor' , '83':'satisfactor', '82':'satisfactor', '233' :'poor' ,'205' :'poor' , '78':'satisfactor', '70':'satisfactor', '211' :'poor' , '179':'moderate', '91':'satisfactor', '49':'good', '134':'moderate', '161':'moderate', '223' :'poor' ,'57':'satisfactor', '73':'satisfactor', '207' :'poor' , '184':'moderate', '48' :'good', '6' :'good', '7' :'good', '194':'moderate', '21' :'good', '50' :'good', '231' :'poor' ,'175':'moderate', '45' :'good', '86':'satisfactor', '243' :'poor' , '232' :'poor' , '18' :'good', '31' :'good', '95':'satisfactor', '237' :'poor' , '217' :'poor' ,'99':'satisfactor', '33' :'good', '176':'moderate', '22' :'good', '29' :'good', '107':'moderate', '17' :'good', '75':'satisfactor', '220' :'poor' , '165':'moderate','149':'moderate', '3' :'good', '245' :'poor' , '239' :'poor' , '72':'satisfactor', '77':'satisfactor', '208' :'poor' , '24' :'good', '198':'moderate', '153':'moderate','53':'satisfactor', '228' :'poor' , '186':'moderate', '51':'satisfactor', '247' :'poor' , '219' :'poor' , '100':'satisfactor', '36' :'good', '204' :'poor' , '30' :'good','221' :'poor' , '229' :'poor' , '187':'moderate', '56':'satisfactor', '230' :'poor' , '192':'moderate', '114':'moderate', '274' :'poor' , '236' :'poor' ,'222' :'poor' , '206' :'poor' , '174':'moderate', '58':'satisfactor', '235' :'poor' , '212' :'poor' , '120':'moderate', '148':'moderate', '242' :'poor' ,'215' :'poor' , '80':'satisfactor', '79':'satisfactor', '67':'satisfactor', '40' :'good', '35' :'good', '185':'moderate', '101':'moderate', '46' :'good', '209' :'poor' ,'169':'moderate', '12' :'good', '47' :'good', '227' :'poor' , '200' :'moderate' , '244' :'poor' , '238' :'poor' , '160':'moderate', '282' :'poor' , '218' :'poor' ,'261' :'poor' , '262' :'poor' , '260' :'poor' , '256' :'poor' , '252' :'poor' , '162':'moderate', '172':'moderate', '156':'moderate', '133':'moderate','116':'moderate', '193':'moderate', '123':'moderate', '65':'satisfactor', '96':'satisfactor', '173':'moderate', '103':'moderate', '8' :'good', '273' :'poor' , '275' :'poor' ,'283' :'poor' , '276' :'poor' , '254' :'poor' , '152':'moderate', '105':'moderate', '64':'satisfactor', '0' :'good', '76':'satisfactor', '127':'moderate', '97':'satisfactor','115':'moderate', '150':'moderate', '142':'moderate', '41' :'good', '102':'moderate', '90':'satisfactor', '132':'moderate', '98':'satisfactor', '199':'moderate', '191':'moderate','157':'moderate', '139':'moderate', '94':'satisfactor', '110':'moderate', '270' :'poor' , '268' :'poor' , '281' :'poor' , '265' :'poor' , '267' :'poor' ,'269' :'poor' , '81':'satisfactor', '128':'moderate', '146':'moderate', '145':'moderate', '129':'moderate', '85':'satisfactor', '117':'moderate', '108':'moderate', '154':'moderate','131':'moderate', '255' :'poor' , '257' :'poor' , '88':'satisfactor', '113':'moderate', '118':'moderate', '167':'moderate', '164':'moderate', '137':'moderate','135':'moderate', '138':'moderate', '109':'moderate', '60':'satisfactor', '177':'moderate', '271' :'poor' , '170':'moderate', '144':'moderate', '166':'moderate','155':'moderate', '136':'moderate', '151':'moderate', '89':'satisfactor', '119':'moderate', '266' :'poor' , '264' :'poor' , '251' :'poor' , '253' :'poor' ,'259' :'poor' , '163':'moderate', '159':'moderate', '241' :'poor' , '214' :'poor' , '122':'moderate', '234' :'poor' , '195':'moderate', '130':'moderate','216' :'poor' , '213' :'poor' , '121':'moderate', '112':'moderate', '168':'moderate', '201' :'poor' , '141':'moderate', '181':'moderate', '143':'moderate','126':'moderate', '182':'moderate', '178':'moderate', '158':'moderate', '140':'moderate', '183':'moderate', '92':'satisfactor', '180':'moderate', '147':'moderate', '55':'satisfactor','184':'moderate'})
#df['AOI_PD']=df.AQI_Bucket.map({'Moderate':3 ,'Good':1,'Poor':0 ,'Satisfactory':4, 'Severe':5 ,'Very Poor':0}) 

In [51]:
df.columns
df.head(50)
from sklearn.svm import SVC
s = SVC()

s.fit(X_train,y_train)

predicts = s.predict(X_test)



City        Date   PM2.5    PM10     NO    NO2    NOx    NH3    CO  \
2123  Amaravati  2017-11-25   81.40  124.50   1.44  20.50  12.08  10.72  0.12   
2124  Amaravati  2017-11-26   78.32  129.06   1.26  26.00  14.85  10.28  0.14   
2125  Amaravati  2017-11-27   88.76  135.32   6.60  30.85  21.77  12.91  0.11   
2126  Amaravati  2017-11-28   64.18  104.09   2.56  28.07  17.01  11.42  0.09   
2127  Amaravati  2017-11-29   72.47  114.84   5.23  23.20  16.59  12.25  0.16   
2128  Amaravati  2017-11-30   69.80  114.86   4.69  20.17  14.54  10.95  0.12   
2129  Amaravati  2017-12-01   73.96  113.56   4.58  19.29  13.97  10.95  0.10   
2130  Amaravati  2017-12-02   89.90  140.20   7.71  26.19  19.87  13.12  0.10   
2131  Amaravati  2017-12-03   87.14  130.52   0.97  21.31  12.12  14.36  0.15   
2132  Amaravati  2017-12-04   84.64  125.00   4.02  26.98  17.58  14.41  0.18   
2133  Amaravati  2017-12-05   88.36  121.77   3.70  20.23  13.75  13.72  0.12   
2134  Amaravati  2017-12-06   96.83  139.36   1.60  25.65  14.99  15.12  0.11   
2135  Amaravati  2017-12-07  117.46  181.64   4.26  41.10  25.32  17.34  0.13   
2136  Amaravati  2017-12-08  122.88  208.86   5.56  54.87  33.71  17.96  0.27   
2137  Amaravati  2017-12-09   74.28  141.22   6.10  44.97  28.88  15.73  0.09   
2138  Amaravati  2017-12-10   50.32  102.77   1.73  33.85  19.41  12.56  0.10   
2139  Amaravati  2017-12-11   58.47  115.27   4.93  41.64  26.15  15.20  0.16   
2140  Amaravati  2017-12-12   89.35  131.48   7.97  42.10  28.88  21.24  0.24   
2141  Amaravati  2017-12-13   64.42   99.74   7.20  34.78  24.36  17.63  0.15   
2142  Amaravati  2017-12-14   69.40   98.94   5.81  29.97  20.67  19.34  0.14   
2143  Amaravati  2017-12-15   71.07  109.65   4.19  25.00  16.70  16.00  0.10   
2144  Amaravati  2017-12-16   79.76  129.81   8.77  40.92  28.84  15.56  0.17   
2145  Amaravati  2017-12-17  108.06  167.62   7.29  47.05  30.94  18.52  0.08   
2146  Amaravati  2017-12-18  100.75  172.04   7.63  53.94  33.45  18.49  0.11   
2147  Amaravati  2017-12-19  106.25  171.56   2.74  43.09  21.78  19.66  0.13   
2148  Amaravati  2017-12-20   83.79  141.83   6.77  47.47  30.74  17.37  0.30   
2149  Amaravati  2017-12-21   79.98  147.74   7.02  49.55  32.07  17.28  0.14   
2150  Amaravati  2017-12-22   76.27  152.59   7.51  56.00  35.90  19.53  0.15   
2151  Amaravati  2017-12-23   86.50  147.95   5.24  42.00  26.60  20.78  0.15   
2152  Amaravati  2017-12-24  100.62  167.75   3.75  47.68  28.41  23.68  0.22   
2153  Amaravati  2017-12-25  110.73  171.47   1.69  31.06  17.89  21.66  0.10   
2154  Amaravati  2017-12-26  107.70  170.21   4.97  43.54  27.20  22.52  0.17   
2155  Amaravati  2017-12-27  104.81  192.20   9.59  63.48  41.57  21.06  0.23   
2156  Amaravati  2017-12-28   89.95  175.16  10.95  64.53  43.23  18.87  0.27   
2157  Amaravati  2017-12-29   74.58  138.60   6.14  46.65  29.81  18.20  0.17   
2158  Amaravati  2017-12-30   56.68  109.33   4.60  33.26  21.44  16.86  0.10   
2159  Amaravati  2017-12-31   61.03  131.62   5.51  39.50  25.49  17.82  0.08   
2160  Amaravati  2018-01-01   59.03  108.83   3.45  23.36  15.23  18.03  0.09   
2161  Amaravati  2018-01-02   61.88  109.82   3.87  23.14  15.45  19.57  0.09   
2162  Amaravati  2018-01-03   71.57  137.48   5.01  39.99  25.36  25.61  0.09   
2163  Amaravati  2018-01-04   92.44  174.75   5.84  53.79  33.36  19.45  0.11   
2164  Amaravati  2018-01-05   92.90  162.69   6.38  56.39  35.19  21.02  0.08   
2165  Amaravati  2018-01-06   85.15  151.97  11.05  61.55  41.72  18.71  0.07   
2166  Amaravati  2018-01-07   81.47  145.68   6.45  46.90  30.18  20.18  0.07   
2167  Amaravati  2018-01-08   81.58  132.66   3.97  34.93  21.81  21.59  0.09   
2168  Amaravati  2018-01-09   79.56  146.64   4.44  37.58  23.60  17.71  0.05   
2169  Amaravati  2018-01-10   87.43  155.95   3.90  37.31  23.02  22.35  0.10   
2170  Amaravati  2018-01-11   87.33  153.97   3.95  42.52  25.82  23.66  0.08   
2171  Amaravati  2018-01-12  110.39  182.5

In [10]:
#df.drop(['AQI_Bucket','Date'],axis=1)
del df["Date"]


In [11]:
del df["AQI_Bucket"]
#X = df.drop(labels='AQI', axis=1)
X = df.iloc[:, :-1].values
#Response variable
y = df.iloc[:, -1].values

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X[10]


array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 88.36, 121.77, 3.7,
       20.23, 13.75, 13.72, 0.12, 14.02, 117.93, 0.24, 2.92, 0.03],
      dtype=object)

In [12]:
y = y.reshape(len(y),1)
print(y)

[[184.]
 [197.]
 [198.]
 ...
 [ 70.]
 [ 68.]
 [ 54.]]


In [13]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

sc_y = StandardScaler()

X = sc_X.fit_transform(X)

y = sc_y.fit_transform(y)

In [14]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set.
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef, cohen_kappa_score, accuracy_score, average_precision_score, roc_auc_score
print(X)

X.shape


[[ 2.94164083 -0.3370036  -0.2156022  ... -0.69153128 -0.31121784
  -0.55074012]
 [ 2.94164083 -0.3370036  -0.2156022  ... -0.68758008 -0.19319961
  -0.54632968]
 [ 2.94164083 -0.3370036  -0.2156022  ... -0.67375088 -0.21924501
  -0.53750881]
 ...
 [-0.33994633 -0.3370036  -0.2156022  ... -0.58484888 -0.66038901
  -0.4801731 ]
 [-0.33994633 -0.3370036  -0.2156022  ... -0.72906768 -0.83945115
  -0.56397144]
 [-0.33994633 -0.3370036  -0.2156022  ... -0.73104328 -0.84026507
  -0.56397144]]


(6236, 21)

In [15]:
print(y)
y.shape



[[ 0.46898787]
 [ 0.60917773]
 [ 0.61996156]
 ...
 [-0.76036931]
 [-0.78193697]
 [-0.93291066]]


(6236, 1)

In [16]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [17]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1, 0, 0, 0, 0, 0, 0, 0, 0, '81.4', '124.5', '1.44', '20.5', '12.08', '10.72', '0.12', '15.24', '127.09', '0.2', '6.5', '0.06']])))

array([193.30808096])

In [21]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 88.36, 121.77, 3.7,
       20.23, 13.75, 13.72, 0.12, 14.02, 117.93, 0.24, 2.92, 0.03]])))

array([191.53020402])

In [22]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,64.18, 104.09, 2.56, 28.07, 17.01, 11.42, 0.09 ,19.00, 138.18, 0.17 ,5.02, 0.07 ]])))

array([191.14412882])

In [31]:

import matplotlib.pyplot as plt

X_grid=np.logical_and(min(sc_X.inverse_transform(X)), max(sc_X.inverse_transform(X)))
#X_grid = np.logical_and(np.arange(min(sc_X.inverse_transform(X))), np.logical_and(max(sc_X.inverse_transform(X))), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_X.transform(X_grid))), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()